@ECHO OFF
SET MANDATUM=ROSARIO.EXE
SET MODUS=WIN32\RELEASE

IF "%1" == "-h" GOTO DEMONSTRA_USUI
IF "%1" NEQ "" SET MODUS="%1"

IF NOT EXIST ..\DESTINATUM\%MODUS%\%MANDATUM% GOTO DEMONSTRA_USUI

:REPETE
..\DESTINATUM\%MODUS%\%MANDATUM%
GOTO REPETE

:DEMONSTRA_USUI
ECHO Ut mandato repetitur, dic: %0 [MODUS]
ECHO Exempli gratia: %0 x64\release

EXIT /B 0